### ISSUE TITLE
Request to move repo under NW Userland

### ISSUE THREAD

**Issue by ayushmanchhabra** [vshjxyz/nwjs-print-server#2]
Hi @vshjxyz,

I'm part of a GitHub org called [NW Utils](https://github.com/nwutils). I'm trying to consolidate NW tooling so it's easier to find useful projects and give much needed life to stagnant ones. I also think this would be a great opportunity to exchange ideas and learn new things. Let me know what you think and if you’d be willing to.

Best Regards
Ayushman

**Comment by vshjxyz** [comment]
Hello @ayushmxn, thanks for checking this out! this repo is a bit ancient and I'm not entirely sure it would still work (I don't have access to raw printers anymore nor time to check it in the near future) but it might still be helpful as an example, I would be glad to move it under a bigger umbrella (as long as I can potentially contribute in the future), let me know what the next steps would be

**Comment by ayushmanchhabra** [comment]
Ah ok. I'll look into raw printing and if I'm able to support it. This looks like a really interesting example of how to use NW.js!

**Comment by ayushmanchhabra** [comment]
I've invited you to the NW Utils org. Once you transfer the repo, I'll add you as the admin for it. Nothing really changes except it's easier to find!

**Comment by ayushmanchhabra** [comment]
Set you as admin of the repo!
